### ISSUE TITLE
How to get  tracker_id from source_id

### ISSUE THREAD

**Issue by tessSnap** [SquareGPS/navixy-api#63]
Hello,
We are integrating the Navixy Tracking Api with our Software, in the documentation , when using the Websocket  on subscribing to the event we see that it returns an object of the get_state method. In this object, there is no tracker_id which we can use to retrieve the assset information at our end. There is only a source_id. How do we get the tracker_id from the Websocket event ?

Api endpoint : https://developers.navixy.com/backend-api/websocket/events/

**Comment by fenik17** [comment]
Hi @tessSnap,
First you need to get a [list of trackers](https://developers.navixy.com/backend-api/resources/tracking/tracker/#list). Using the answer, you will be able to create a map [`source_id -> tracker_id`].

**Comment by tessSnap** [comment]
Thank you @fenik17
