### ISSUE TITLE
The answer is empty

### ISSUE THREAD

**Issue by miguelbanda8** [SquareGPS/navixy-api#71]
Hello:
I am sending a GET sentence using Postman (as you can see on the
attached file), I received  the reply, but the list is empty.

The sentence is a GET:
https://trackerexpress.softwarexpress.pe/api-v2/task/route/list?hash=6ac******

The same answer is received when I use:
https://trackerexpress.softwarexpress.pe/api-v2/task/route/list?hash=*******

**Comment by john9x** [comment]
Hi!

You have no created task routes. So what response you expect?

P.S. You should immediately change your password to invalidate sessions due to its compromentation. Session key aka hash it's a secret information.

**Comment by miguelbanda8** [comment]
Please, can you tell me the name of the task and forms API? Do I am calling them properly?
