### ISSUE TITLE
Calling APIs

### ISSUE THREAD

**Issue by miguelbanda8** [SquareGPS/navixy-api#72]
Please, can you tell me the name of the task and forms APIs? Do I am calling them properly?

I am using https://MYDOMAIN/api-v2/task/route/list

**Comment by john9x** [comment]
https://developers.navixy.com/backend-api/resources/field_service/task/
https://developers.navixy.com/backend-api/resources/field_service/form/

[/task/route/list](https://developers.navixy.com/backend-api/resources/field_service/task/route/#list) - it's a call to list task routes.
